using System.Collections;
using System.Collections.Generic;
using UnityEngine;

public class Trap : MonoBehaviour
{
    public float bounceForce = 10f;
    public int damage =1;
    // Start is called before the first frame update
    private void OnTriggerEnter2D (Collider2D collision)
    {
        if ( collision.gameObject.CompareTag("Player"))
        {
            HandlePlayerBounce(collision.gameObject);
        }
    }

    // Update is called once per frame
    private void HandlePlayerBounce(GameObject player)
    {
     Rigidbody2D rb =player.GetComponent<Rigidbody2D>();

     if(rb){
        rb.velocity = new Vector2(rb.velocity.x, 0f);

        rb.AddForce(Vector2.up * bounceForce, ForceMode2D.Impulse);
     }   
    }
}
